In [3]:
# --- Part 3: Task 1 - File Read & Write Basics ---

filename = "python_notes.txt"

# --- Part A: Write & Append ---

# 1. Writing the initial 5 topics in 'w' mode
initial_notes = [
    "Topic 1: Variables store data. Python is dynamically typed.",
    "Topic 2: Lists are ordered and mutable.",
    "Topic 3: Dictionaries store key-value pairs.",
    "Topic 4: Loops automate repetitive tasks.",
    "Topic 5: Exception handling prevents crashes."
]

try:
    with open(filename, "w", encoding="utf-8") as f:
        for line in initial_notes:
            f.write(line + "\n")
    print("✅ File written successfully.")

    # 2. Appending two custom lines in 'a' mode
    extra_notes = [
        "Topic 6: File I/O allows data persistence.",
        "Topic 7: APIs enable communication between different software."
    ]
    
    with open(filename, "a", encoding="utf-8") as f:
        for line in extra_notes:
            f.write(line + "\n")
    print("✅ Lines appended.")

except Exception as e:
    print(f"❌ Error during file operations: {e}")


# --- Part B: Read & Search ---

print("\n--- Reading python_notes.txt ---")

try:
    with open(filename, "r", encoding="utf-8") as f:
        lines = f.readlines()
        
    # 1. Print each line numbered and stripped
    for i, line in enumerate(lines, 1):
        print(f"{i}. {line.strip()}")

    # 2. Print total number of lines
    print(f"\nTotal number of lines in file: {len(lines)}")

    # 3. Keyword Search (Case-insensitive)
    keyword = input("\nEnter a keyword to search in the notes: ").strip().lower()
    matches = [line.strip() for line in lines if keyword in line.lower()]

    if matches:
        print(f"🔍 Found {len(matches)} match(es) for '{keyword}':")
        for match in matches:
            print(f"-> {match}")
    else:
        print(f"ℹ️ No lines contain the keyword: '{keyword}'.")

except FileNotFoundError:
    print(f"❌ Error: The file '{filename}' was not found.")

✅ File written successfully.
✅ Lines appended.

--- Reading python_notes.txt ---
1. Topic 1: Variables store data. Python is dynamically typed.
2. Topic 2: Lists are ordered and mutable.
3. Topic 3: Dictionaries store key-value pairs.
4. Topic 4: Loops automate repetitive tasks.
5. Topic 5: Exception handling prevents crashes.
6. Topic 6: File I/O allows data persistence.
7. Topic 7: APIs enable communication between different software.

Total number of lines in file: 7
🔍 Found 1 match(es) for 'python':
-> Topic 1: Variables store data. Python is dynamically typed.


Technical Explanation: File I/O Basics (Part 3 - Task 1)
This task demonstrates how Python interacts with the local file system using built-in functions.

1. File Access Modes
'w' (Write Mode): Opens the file for writing. If the file already exists, it truncates (deletes) the content first. If it doesn't exist, it creates a new one.

'a' (Append Mode): Opens the file and keeps the existing data, adding new content to the end of the file.

'r' (Read Mode): Opens the file specifically for reading data.

2. Context Manager (with statement)
Using with open(...) is the best practice in Python. It automatically handles the closing of the file, even if an error occurs during the process. This prevents "File in use" errors and memory leaks.

3. Encoding (utf-8)
Explicitly setting encoding="utf-8" ensures that the file is cross-platform compatible. It allows the script to handle special characters or emojis consistently across Windows, Mac, and Linux.

4. String Cleaning & Searching
.strip(): Used during reading to remove the trailing \n (newline) character, preventing double-spacing in the output.

Case-Insensitive Search: By converting both the file content and the user input to .lower(), we ensure that a search for "python" matches "Python", "PYTHON", or "pYtHoN".

In [4]:
import requests

# --- Part 3: Task 2 - API Integration ---

BASE_URL = "https://dummyjson.com/products"

# Step 1 — Fetch and Display 20 Products
print("--- Step 1: Fetching 20 Products ---")
try:
    response = requests.get(f"{BASE_URL}?limit=20")
    response.raise_for_status()  # Check for HTTP errors
    data = response.json()
    products = data.get("products", [])

    # Print Formatted Table Header
    print(f"{'ID':<4} | {'Title':<30} | {'Category':<15} | {'Price':<8} | {'Rating'}")
    print("-" * 75)

    for p in products:
        print(f"{p['id']:<4} | {p['title'][:30]:<30} | {p['category']:<15} | ${p['price']:<7} | {p['rating']}")

    # Step 2 — Filter and Sort
    print("\n--- Step 2: High-Rated Products (Rating >= 4.5) Sorted by Price (Desc) ---")
    
    # Filter products with rating >= 4.5
    high_rated = [p for p in products if p['rating'] >= 4.5]
    
    # Sort by price in descending order
    sorted_high_rated = sorted(high_rated, key=lambda x: x['price'], reverse=True)

    for p in sorted_high_rated:
        print(f"Price: ${p['price']:<7} | Rating: {p['rating']} | Title: {p['title']}")

    # Step 3 — Search by Category (Laptops)
    print("\n--- Step 3: Laptops Category ---")
    laptop_res = requests.get(f"{BASE_URL}/category/laptops")
    laptop_data = laptop_res.json()
    laptops = laptop_data.get("products", [])

    for laptop in laptops:
        print(f"Laptop: {laptop['title']:<25} | Price: ${laptop['price']}")

    # Step 4 — POST Request (Simulated)
    print("\n--- Step 4: Simulated POST Request ---")
    new_product = {
        "title": "My Custom Product",
        "price": 999,
        "category": "electronics",
        "description": "A product I created via API"
    }

    post_res = requests.post(f"{BASE_URL}/add", json=new_product)
    print("Server Response for POST:")
    print(post_res.json())

except requests.exceptions.RequestException as e:
    print(f"❌ API Error occurred: {e}")

--- Step 1: Fetching 20 Products ---
ID   | Title                          | Category        | Price    | Rating
---------------------------------------------------------------------------
1    | Essence Mascara Lash Princess  | beauty          | $9.99    | 2.56
2    | Eyeshadow Palette with Mirror  | beauty          | $19.99   | 2.86
3    | Powder Canister                | beauty          | $14.99   | 4.64
4    | Red Lipstick                   | beauty          | $12.99   | 4.36
5    | Red Nail Polish                | beauty          | $8.99    | 4.32
6    | Calvin Klein CK One            | fragrances      | $49.99   | 4.37
7    | Chanel Coco Noir Eau De        | fragrances      | $129.99  | 4.26
8    | Dior J'adore                   | fragrances      | $89.99   | 3.8
9    | Dolce Shine Eau de             | fragrances      | $69.99   | 3.96
10   | Gucci Bloom Eau de             | fragrances      | $79.99   | 2.74
11   | Annibale Colombo Bed           | furniture       | $1899.99 | 4.7

Technical Explanation: API Integration (Part 3 - Task 2)
In this task, we transitioned from local file handling to Network I/O using the requests library to interact with a RESTful API.

1. Understanding HTTP Methods
GET: Used to retrieve data from the server. We used this to fetch the product list and specific categories.

POST: Used to send data to a server to create a resource. While DummyJSON is a mock API, the process mimics a real production environment where a database would be updated.

2. JSON Parsing
APIs typically return data in JSON (JavaScript Object Notation) format. In Python, we use the .json() method to convert this string-based response into a Python Dictionary or List, making it easy to iterate and filter.

3. Data Transformation (Filtering & Sorting)
List Comprehensions: We used [p for p in products if p['rating'] >= 4.5] to efficiently filter data based on specific criteria.

sorted() with Lambda: To sort complex dictionaries, we provide a key using a lambda function: key=lambda x: x['price']. This tells Python specifically which field to use for the comparison.

4. API Error Resilience
We included response.raise_for_status(). This is a critical safety feature that automatically triggers an exception if the server returns an error code (like 404 Not Found or 500 Internal Server Error), preventing the script from processing "garbage" data.

In [5]:
import requests

# --- Part A: Guarded Calculator ---
def safe_divide(a, b):
    try:
        return a / b
    except ZeroDivisionError:
        return "Error: Cannot divide by zero"
    except TypeError:
        return "Error: Invalid input types"

print("--- Task 3A: Testing Guarded Calculator ---")
print(f"10 / 2     -> {safe_divide(10, 2)}")
print(f"10 / 0     -> {safe_divide(10, 0)}")
print(f"'ten' / 2  -> {safe_divide('ten', 2)}")


# --- Part B: Guarded File Reader ---
def read_file_safe(filename):
    try:
        with open(filename, "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")
        return None
    finally:
        print("File operation attempt complete.")

print("\n--- Task 3B: Testing Guarded File Reader ---")
# Testing with existing file from Task 1
content = read_file_safe("python_notes.txt")
if content: print("File read successfully.")

# Testing with non-existent file
read_file_safe("ghost_file.txt")


# --- Part C: Robust API Calls ---
def make_robust_request(method, url, **kwargs):
    """Utility function to handle API-level Python exceptions."""
    try:
        if method.upper() == "GET":
            response = requests.get(url, timeout=5, **kwargs)
        else:
            response = requests.post(url, timeout=5, **kwargs)
        return response
    except requests.exceptions.ConnectionError:
        print("Connection failed. Please check your internet.")
    except requests.exceptions.Timeout:
        print("Request timed out. Try again later.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")
    return None


# --- Part D: Input Validation Loop & HTTP Status Checking ---
print("\n--- Task 3D: Product Lookup Tool ---")

while True:
    user_input = input("\nEnter a product ID to look up (1–100), or 'quit' to exit: ").strip().lower()
    
    if user_input == 'quit':
        print("Exiting Lookup Tool.")
        break
    
    # 1. Validation (Range 1-100)
    if not user_input.isdigit():
        print("⚠️ Warning: Please enter a valid integer.")
        continue
    
    product_id = int(user_input)
    if not (1 <= product_id <= 100):
        print("⚠️ Warning: ID must be between 1 and 100.")
        continue
        
    # 2. API Call using Robust logic
    url = f"https://dummyjson.com/products/{product_id}"
    response = make_robust_request("GET", url)
    
    # 3. Check HTTP Status Codes
    if response:
        if response.status_code == 200:
            product = response.json()
            print(f"✅ Found: {product['title']} | Price: ${product['price']}")
        elif response.status_code == 404:
            print("❌ Product not found.")
        else:
            print(f"⚠️ Unexpected Server Response: {response.status_code}")

--- Task 3A: Testing Guarded Calculator ---
10 / 2     -> 5.0
10 / 0     -> Error: Cannot divide by zero
'ten' / 2  -> Error: Invalid input types

--- Task 3B: Testing Guarded File Reader ---
File operation attempt complete.
File read successfully.
Error: File 'ghost_file.txt' not found.
File operation attempt complete.

--- Task 3D: Product Lookup Tool ---
✅ Found: Water | Price: $0.99
✅ Found: Nike Air Jordan 1 Red And Black | Price: $149.99
✅ Found: Dog Food | Price: $10.99
✅ Found: Eyeshadow Palette with Mirror | Price: $19.99
✅ Found: Tissue Paper Box | Price: $2.49
⚠️ Warning: ID must be between 1 and 100.
✅ Found: Dog Food | Price: $10.99
✅ Found: Green Bell Pepper | Price: $1.29
Exiting Lookup Tool.


Technical Explanation: Exception Handling & Robustness (Part 3 - Task 3)
This task demonstrates how to transition from code that "just works" to code that is "production-ready" by anticipating and managing failures.

1. Granular Exception Handling
In Part A, we catch specific errors like ZeroDivisionError and TypeError. This is better than a "catch-all" block because it allows the program to provide precise feedback to the user, helping them understand exactly why an operation failed.

2. The finally Block
In Part B, we use finally. This block is guaranteed to execute regardless of whether an exception was raised or caught. It is typically used for "cleanup" tasks, such as closing database connections or logging that an attempt was made.

3. Python Exceptions vs. HTTP Status Codes
There is a vital distinction made in Part C & D:

Python Exceptions (ConnectionError, Timeout): These happen when the "pipe" is broken (e.g., your Wi-Fi is off). The program stops immediately unless caught in a try-except.

HTTP Status Codes (404, 200): These happen when the "pipe" is working, but the server has a specific message for you. A 404 is not a crash; it is a valid response from the server saying "I couldn't find what you asked for." We handle these using if response.status_code == ....

4. Input Validation (The "Guard" Pattern)
In Part D, we implement "Defensive Programming." We validate the user's input before making the expensive network call. Checking if a string is a digit and within the correct range saves bandwidth and prevents unnecessary server load.

In [6]:
import requests
from datetime import datetime

# --- Task 4: Logging to File ---

LOG_FILE = "error_log.txt"

def log_error(function_name, error_type, message):
    """Utility to write timestamped errors to a text file."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_entry = f"[{timestamp}] ERROR in {function_name}: {error_type} — {message}\n"
    
    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write(log_entry)
    print(f"📝 Logged to {LOG_FILE}: {error_type}")

# --- Triggering Intentional Errors ---

print("--- Task 4: Starting Intentional Error Triggers ---")

# 1. Trigger a Python ConnectionError (Unreachable URL)
try:
    fake_url = "https://this-host-does-not-exist-xyz.com/api"
    print(f"Attempting to connect to: {fake_url}...")
    requests.get(fake_url, timeout=3)
except requests.exceptions.ConnectionError as e:
    log_error("fetch_products", "ConnectionError", "No connection could be made to host")
except Exception as e:
    log_error("fetch_products", "UnexpectedError", str(e))

# 2. Trigger an HTTP 404 Error (Product ID 999)
try:
    invalid_id = 999
    url = f"https://dummyjson.com/products/{invalid_id}"
    print(f"\nRequesting non-existent Product ID: {invalid_id}...")
    response = requests.get(url, timeout=5)
    
    # Manually check for 404 because it is NOT a Python exception
    if response.status_code != 200:
        log_error("lookup_product", "HTTPError", f"{response.status_code} Not Found for product ID {invalid_id}")
    else:
        print("Success (Unexpectedly!)")
except Exception as e:
    log_error("lookup_product", "Exception", str(e))

# --- Final Step: Read and Print the Log File ---
print("\n" + "="*50)
print(f"READING {LOG_FILE} CONTENTS:")
print("="*50)

try:
    with open(LOG_FILE, "r", encoding="utf-8") as f:
        print(f.read())
except FileNotFoundError:
    print("The log file was not found. Check if the logging logic executed correctly.")

--- Task 4: Starting Intentional Error Triggers ---
Attempting to connect to: https://this-host-does-not-exist-xyz.com/api...
📝 Logged to error_log.txt: ConnectionError

Requesting non-existent Product ID: 999...
📝 Logged to error_log.txt: HTTPError

READING error_log.txt CONTENTS:
[2026-04-02 15:59:38] ERROR in fetch_products: ConnectionError — No connection could be made to host
[2026-04-02 15:59:39] ERROR in lookup_product: HTTPError — 404 Not Found for product ID 999



Technical Explanation: Persistent Error Logging (Part 3 - Task 4)
This task demonstrates the industry-standard way of tracking application health through Logging.

1. Timestamping with datetime
We use datetime.now().strftime("%Y-%m-%d %H:%M:%S"). This converts a Python datetime object into a human-readable string. In a production environment, timestamps are vital for correlating errors with specific events or server downtime.

2. Append Mode ('a')
Using 'a' ensures that we don't wipe out previous logs. This allows us to see a history of what went wrong over days or weeks. If we used 'w', we would only ever see the most recent error.

3. Exception vs. Response Status
Python Exceptions: When we try to reach this-host-does-not-exist-xyz.com, the network stack fails, throwing a ConnectionError. This is a Python-level crash that requires try-except.

HTTP Error Codes: When we ask for product 999, the server responds successfully with a code 404. Since the communication was successful, Python does not see this as an "error." We must manually detect this by checking response.status_code and log it ourselves.